"""initial migration with read only data

Revision ID: aadebda42139
Revises:
Create Date: 2021-05-25 17:45:46.300047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadebda42139'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    asset_class_table = op.create_table('asset_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.Enum('dove', 'rapideye', 'skysat', 'dish', 'yagi', name='assetclasschoice'), nullable=False),
    sa.Column('class_type', sa.Enum('satellite', 'antenna', name='typechoice'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_class'], ['asset_class.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.bulk_insert(asset_class_table,
        [
            {'id': 1, 'class_name': 'dove', 'class_type': 'satellite'},
            {'id': 2, 'class_name': 'rapideye', 'class_type': 'satellite'},
            {'id': 3, 'class_name': 'skysat', 'class_type': 'satellite'},
            {'id': 4, 'class_name': 'dish', 'class_type': 'antenna'},
            {'id': 5, 'class_name': 'yagi', 'class_type': 'antenna'},
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset')
    op.drop_table('asset_class')
    # ### end Alembic commands ###
